import LeftZurag from "../assets/red.webp"
import MiddleZurag from "../assets/green.webp"
import RightZurag from "../assets/blue.webp"
export default [ 
    { 
        id:"1", 
        name:"TITLE1", 
        img: {LeftZurag},
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
        description2: "     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
        description3: "     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
        description4: "     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
    }, 
    { 
        id:"2", 
        name:"TITLE2", 
        img: {MiddleZurag},
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
        description2: "     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
        description3: "     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
        description3: "     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
    }, 
    { 
        id:"3", 
        name:"TITLE3", 
        img: {RightZurag},
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
        description2: "     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
        description3: "     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
        description3: "     Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos culpa laboriosam distinctio beatae! Perferendis asperiores quasi necessitatibus laborum odit commodi ipsum natus in laboriosam accusantium quas tenetur suscipit neque eius blanditiis dolor dolore enim, consequatur illum quis magnam, ipsam sed sunt sint. Reprehenderit, placeat? Aspernatur quos laborum mollitia! Commodi laborum voluptatum voluptas, sint modi quam adipisci! Quo asperiores nisi repudiandae culpa accusantium dolores eius, officiis rerum, earum sint exercitationem.", 
    }, 
]